// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3jqdNd-kPYAu9gVP3QUdgRJSfqY3uaU0',
    appId: '1:1099073623189:web:2450c5c8036b0261b8379c',
    messagingSenderId: '1099073623189',
    projectId: 'vjti-previous-years',
    authDomain: 'vjti-previous-years.firebaseapp.com',
    databaseURL: 'https://vjti-previous-years-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vjti-previous-years.appspot.com',
    measurementId: 'G-HLL3F3M9YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOPGpqZujqkfV8lST0N9bQYzTLzF5ymvM',
    appId: '1:1099073623189:android:ee7e807f79e30b19b8379c',
    messagingSenderId: '1099073623189',
    projectId: 'vjti-previous-years',
    databaseURL: 'https://vjti-previous-years-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vjti-previous-years.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVkc6LBuMlS7x1hqMqb8QV6-bskonSWd0',
    appId: '1:1099073623189:ios:3996011fff076832b8379c',
    messagingSenderId: '1099073623189',
    projectId: 'vjti-previous-years',
    databaseURL: 'https://vjti-previous-years-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vjti-previous-years.appspot.com',
    iosClientId: '1099073623189-vdtgbhlnpvcvpj00loocaqfk1udlfub4.apps.googleusercontent.com',
    iosBundleId: 'com.example.vjtiPrevious',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVkc6LBuMlS7x1hqMqb8QV6-bskonSWd0',
    appId: '1:1099073623189:ios:3996011fff076832b8379c',
    messagingSenderId: '1099073623189',
    projectId: 'vjti-previous-years',
    databaseURL: 'https://vjti-previous-years-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vjti-previous-years.appspot.com',
    iosClientId: '1099073623189-vdtgbhlnpvcvpj00loocaqfk1udlfub4.apps.googleusercontent.com',
    iosBundleId: 'com.example.vjtiPrevious',
  );
}
